<?php defined( '_JEXEC' ) or die;

ob_start();
//set devmod = false to load static css generated by 
$devmode = true;
include_once JPATH_THEMES . '/' . $this->template . '/logic.php';

$templateCSS = $tpath . '/css/template.min.css';

if ( $devmode ) {
  $templateCSS = $tpath . '/css/template.css.php';
}

?><!doctype html>

<html lang="<?php echo $this->language; ?>">

<head>
  <jdoc:include type="head" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="apple-touch-icon-precomposed" href="<?php echo $tpath; ?>/images/apple-touch-icon-57x57-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $tpath; ?>/images/apple-touch-icon-72x72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $tpath; ?>/images/apple-touch-icon-114x114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $tpath; ?>/images/apple-touch-icon-144x144-precomposed.png">
</head>
  
<body class="<?php echo ( $menu->getActive() == $menu->getDefault() ? 'front' : 'site' ) . ' ' . $active->alias . ' ' . $pageclass; ?>">
  <!--Your code here-->
  
  <link rel="stylesheet" href="<?php echo $templateCSS ?>">
  <?php echo $scripts; ?>
</body>

</html>

<?php

$body = ob_get_clean();
$replace = array(
  //remove tabs before and after HTML tags
  '/\>[^\S ]+/s'   => '>',
  '/[^\S ]+\</s'   => '<',
  //shorten multiple whitespace sequences; keep new-line characters because they matter in JS!!!
  '/([\t ])+/s'  => ' ',
  //remove leading and trailing spaces
  '/^([\t ])+/m' => '',
  '/([\t ])+$/m' => '',
  // remove JS line comments (simple only); do NOT remove lines containing URL (e.g. 'src="http://server.com/"')!!!
  '~//[a-zA-Z0-9 ]+$~m' => '',
  //remove empty lines (sequence of line-end and white-space characters)
  '/[\r\n]+([\t ]?[\r\n]+)+/s'  => "\n",
  //remove empty lines (between HTML tags); cannot remove just any line-end characters because in inline JS they can matter!
  '/\>[\r\n\t ]+\</s'    => '><',
  //remove "empty" lines containing only JS's block end character; join with next line (e.g. "}\n}\n</script>" --> "}}</script>"
  '/}[\r\n\t ]+/s'  => '}',
  '/}[\r\n\t ]+,[\r\n\t ]+/s'  => '},',
  //remove new-line after JS's function or condition start; join with next line
  '/\)[\r\n\t ]?{[\r\n\t ]+/s'  => '){',
  '/,[\r\n\t ]?{[\r\n\t ]+/s'  => ',{',
  //remove new-line after JS's line end (only most obvious and safe cases)
  '/\),[\r\n\t ]+/s'  => '),',
  //remove quotes from HTML attributes that does not contain spaces; keep quotes around URLs!
  //'~([\r\n\t ])?([a-zA-Z0-9]+)="([a-zA-Z0-9_/\\-]+)"([\r\n\t ])?~s' => '$1$2=$3$4', //$1 and $4 insert first white-space character found before/after attribute
);
$body = preg_replace( array_keys( $replace ) , array_values( $replace ) , $body );
echo $body;
